### ISSUE TITLE
The problem appear in vue

### ISSUE THREAD

**Issue by zdd2018** [zxing-js/library#209]
I met this error when used in vue.
```
NotFoundException
    at FinderPatternFinder.selectBestPatterns (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/esm5/core/qrcode/detector/FinderPatternFinder.js:548:19)
    at FinderPatternFinder.find (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/esm5/core/qrcode/detector/FinderPatternFinder.js:167:32)
    at Detector.detect (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/esm5/core/qrcode/detector/Detector.js:68:27)
    at QRCodeReader.decode (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/esm5/core/qrcode/QRCodeReader.js:64:81)
    at BrowserQRCodeReader.BrowserCodeReader.decodeBitmap (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/esm5/browser/BrowserCodeReader.js:878:28)
    at BrowserQRCodeReader.BrowserCodeReader.decode (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/esm5/browser/BrowserCodeReader.js:832:21)
    at loop (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/esm5/browser/BrowserCodeReader.js:782:36)
    at eval (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/esm5/browser/BrowserCodeReader.js:796:64)
    at new Promise (<anonymous>)
    at BrowserQRCodeReader.BrowserCodeReader.decodeOnce (webpack-internal:///./node_modules/_@zxing_library@0.15.1@@zxing/library/e
```
method:
```
    import {BrowserQRCodeReader} from '@zxing/library';

 const codeReader = new BrowserQRCodeReader();
                const img = document.getElementById('img');
                codeReader
                    .decodeFromImage(img)
                    .then(result => console.log(result.text))
                    .catch(err => console.error(err));
```

**Comment by odahcam** [comment]
Just wrap the call into a try-catch block, this kind of exception is expected to be thrown in this version. This is not the end of the world, but the library telling you that it couldn't find any barcodes in the received image.

**Comment by 02jaysenghani** [comment]
thank you

**Comment by barocsi** [comment]
Actually for me it works on desktop, mobile, but on certain chromium enabled devices it simply does not work despite camera stream is visible and throws this error.
