### ISSUE TITLE
executing never finishes and then the image disappears

### ISSUE THREAD

**Issue by westlakem** [zxing-js/library#297]
I have an angular component

```
import { Component, ViewChild, ElementRef } from '@angular/core';
import { BrowserPDF417Reader } from '@zxing/library';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'dl-scan';
  codeReader = new BrowserPDF417Reader();

  @ViewChild('image') image: ElementRef;
  decoded: string;

  decode() {
    this.codeReader.decodeFromImageElement(this.image.nativeElement)
      .then(result => {
        console.log(result);
        this.decoded = result.getText();
      })
      .catch(err => {
        console.error(err);
        this.decoded = err;
      });

    console.log(`Started decode for image`)
  };

}
```

I've got a breakpoint on the nativeElement call and that is referencing the image element correctly.  When I continue from that breakpoint, I never enter the `then` or `catch` statements.  After waiting a few minutes, I tried clicking the button again and I get the following error:

```
app.component.ts:23 NotFoundException: Video stream has ended before any code could be detected.
    at loop (http://localhost:4200/vendor.js:63540:24)
    at http://localhost:4200/vendor.js:63554:60
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:412:35)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:44337:33)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:411:40)
    at Zone.runTask (http://localhost:4200/polyfills.js:180:51)
    at invokeTask (http://localhost:4200/polyfills.js:493:38)
    at ZoneTask.invoke (http://localhost:4200/polyfills.js:482:52)
    at timer (http://localhost:4200/polyfills.js:2565:33)
```
and then the image disappears from the site 

HTML
```
<div id="pdf417-1">
  <div>
    <button (click)="decode()">Decode</button>
  </div>
  <div>
    <img width=480px height=480px #image src="assets/dl.jpg" style="border: 1px solid gray">
  </div>
  <label>Result:</label>
  <blockquote>
    <p class="result">{{decoded}}</p>
  </blockquote>
</div>
```

**Comment by odahcam** [comment]
That would be definitely a bug, could you please setup an example on StackBlitz or something?
