### ISSUE TITLE
ChecksumException 

### ISSUE THREAD

**Issue by hamoha31** [zxing-js/library#361]
**Describe the bug**
It takes too long to correctly scan the QR Code. Most of the times this exceptions shown:
ChecksumException
    at Decoder$2.correctErrors (https://mysite.com/js/zxing.js:12888:23)
    at Decoder$2.decodeBitMatrixParser (https://mysite.com/js/zxing.js:12859:22)
    at Decoder$2.decodeBitMatrix (https://mysite.com/js/zxing.js:12806:29)
    at QRCodeReader.decode (https://mysite.com/js/zxing.js:14268:46)
    at BrowserQRCodeReader.decodeBitmap (https://mysite.com/js/zxing.js:3516:32)
    at BrowserQRCodeReader.decode (https://mysite.com/js/zxing.js:3470:25)
    at loop (https://mysite.com/js/zxing.js:3448:41)

I used all recent versions and some old versions too.
It is on every platform (web and mobile)

**Comment by odahcam** [comment]
This is not a bug, this is just the library's expected behaviour.
