### ISSUE TITLE
ESM5 Build not included anymore?

### ISSUE THREAD

**Issue by DKhalil** [zxing-js/library#366]
Just updated the package to 0.18.2 and cannot import it anymore with the path `@zxing/library/esm5`. Did you remove the esm5 build on purpose or was it just missed with the move to rollup?

**Comment by odahcam** [comment]
Removed on purpose as it didn't make that much of sense. It should be es2015 now and es6 modules should be in esm folder.

**Comment by DKhalil** [comment]
@odahcam well, I'm using it on AWS lambda which as of now only supports node 12.x, and thus I needed esm5 modules

**Comment by slokhorst** [comment]
The `esm` build actually has `"target": "es5"`: https://github.com/zxing-js/library/blob/master/tsconfig.lib-esm.json

**Comment by odahcam** [comment]
1. The `esm` contains ES6 modules and ES5 "classes".
2. The `es2015` contains ES6 modules and ES6 "classes".
3. The `cjs` contains commonJS compatible code.

As per this google document, esm5 (ignoring the F for Flattening) would be:

> The shortened name “FESM” (pronounced “phesom”) can have a number after it such as “FESM5” or “FESM2015”. The number refers to the language level of the JavaScript inside the module. So a FESM5 file would be ESM+ES5 (import/export statements and ES5 source code).

It seems you need the `esm` option, which should be automatically selected by your environment when you import `@zxing/library` based on this setting:

https://github.com/zxing-js/library/blob/6c81a112af440cd6a4f3735c10ac35d34196f0d6/package.json#L43-L48

Although, none of them satisfies your needs? If not, what exactly esm5 modules would you need?

**Comment by DKhalil** [comment]
Sorry for the delay. So it seems to actually work now. However I do get a bunch of warnings:

```
NotFoundException
    at RSSExpandedReader.decodeRow2pairs (/qrcodes/node_modules/@zxing/library/cjs/core/oned/rss/expanded/RSSExpandedReader.js:86:31)
    at RSSExpandedReader.decodeRow (/qrcodes/node_modules/@zxing/library/cjs/core/oned/rss/expanded/RSSExpandedReader.js:62:59)
    at MultiFormatOneDReader.decodeRow (/qrcodes/node_modules/@zxing/library/cjs/core/oned/MultiFormatOneDReader.js:99:40)
    at _loop_1 (/qrcodes/node_modules/@zxing/library/cjs/core/oned/OneDReader.js:137:41)
    at MultiFormatOneDReader.OneDReader.doDecode (/qrcodes/node_modules/@zxing/library/cjs/core/oned/OneDReader.js:159:31)
    at MultiFormatOneDReader.OneDReader.decode (/qrcodes/node_modules/@zxing/library/cjs/core/oned/OneDReader.js:43:25)
    at MultiFormatReader.decodeInternal (/qrcodes/node_modules/@zxing/library/cjs/core/MultiFormatReader.js:194:35)
    at MultiFormatReader.decode (/qrcodes/node_modules/@zxing/library/cjs/core/MultiFormatReader.js:77:21)
    at Jimp.<anonymous> (/qrcodes/index.js:98:34)
    at Timeout._onTimeout (/qrcodes/node_modules/@jimp/core/dist/index.js:264:25) {
  message: undefined
}
```

**Comment by slokhorst** [comment]
`NotFoundException` simply means that no barcode could be found in the image. Although it looks like this specific issue might be fixed by b18c9276e6a7b77863f14785ad5fee6dbc9e36b6. Are you using v0.18.3 or earlier?

**Comment by Swiftwork** [comment]
@DKhalil I suspect it is as @slokhorst says, check out the solution here https://github.com/zxing-js/library/issues/367#issuecomment-723476412 and then comment below 😄.

**Comment by DKhalil** [comment]
Ahhh yes, it is. Thanks!
