### ISSUE TITLE
Unable to decode some QR code

### ISSUE THREAD

**Issue by dodomui** [zxing-js/library#92]
Hi, 

I'm facing some QR code unable to decode by using this library.
Those QR code can be decode by using camera scanner and this zxing online decoder at https://zxing.org/w/decode.jspx

Uploaded one of the QR code that unable to scan.
![whatsapp image 2018-09-17 at 12 36 31 pm](https://user-images.githubusercontent.com/19356577/45606640-56827700-ba79-11e8-92ba-10df6ba561bb.jpeg)

Error as per below:
checksum or format error, trying again... Error
    at t.correctErrors (lib.js:1)
    at t.decodeBitMatrixParser (lib.js:1)
    at t.decodeBitMatrix (lib.js:1)
    at t.decode (lib.js:1)
    at e.t.readerDecode (lib.js:1)
    at e.t.decodeOnce (lib.js:1)
    at lib.js:1
    at new Promise (<anonymous>)
    at e.t.decodeFromImage (lib.js:1)
    at HTMLAnchorElement.document.getElementById.addEventListener ((index):69)

**Comment by odahcam** [comment]
Please provide Library and Browser version. I could decode without problems, just a little waiting of 2s.

**Comment by dodomui** [comment]
Yes, if scan it can work properly.
But I'm using library/docs/examples/qr-image/index.html this method.

Is to read and decode the qrcode image directly.
I'm using Chrome and point lib to https://unpkg.com/@zxing/library@dev.

It showing the error infinitely.
![screen shot 2018-09-18 at 1 37 00 am](https://user-images.githubusercontent.com/19356577/45639774-751d5800-bae3-11e8-9e86-34f56c2e1098.png)

**Comment by dodomui** [comment]
![test0](https://user-images.githubusercontent.com/19356577/45639930-d3e2d180-bae3-11e8-955c-294913fb630a.jpg)
This qrcode image unable to read also.

Actually I'm facing the same problem while using another library (LazarSoft/jsqrcode) wrap from zxing.
Unable to decode image but can scan.

Wonder what is the problem...

**Comment by odahcam** [comment]
Please try with https://unpkg.com/@zxing/library@latest.

**Comment by dodomui** [comment]
There's no error while using https://unpkg.com/@zxing/library@latest.
But the decode result was empty. I'm using this example https://zxing-js.github.io/library/examples/qr-image/

Will try to build a codepen later on.

Below is the previous error code, but doesn't appear anymore on 0.8.3

```
ZXing code reader initialized
BrowserCodeReader.ts:257 true Error
    at t.readVersion (BitMatrixParser.ts:140)
    at t.decodeBitMatrixParser (Decoder.ts:130)
    at t.decodeBitMatrix (Decoder.ts:84)
    at t.decode (QRCodeReader.ts:76)
    at e.t.readerDecode (BrowserCodeReader.ts:278)
    at e.t.decodeOnce (BrowserCodeReader.ts:254)
    at BrowserCodeReader.ts:201
    at new Promise (<anonymous>)
    at e.t.decodeFromImage (BrowserCodeReader.ts:192)
    at HTMLAnchorElement.document.getElementById.addEventListener ((index):70)
BrowserCodeReader.ts:262 checksum or format error, trying again... Error
    at t.readVersion (BitMatrixParser.ts:140)
    at t.decodeBitMatrixParser (Decoder.ts:130)
    at t.decodeBitMatrix (Decoder.ts:84)
    at t.decode (QRCodeReader.ts:76)
    at e.t.readerDecode (BrowserCodeReader.ts:278)
    at e.t.decodeOnce (BrowserCodeReader.ts:254)
    at BrowserCodeReader.ts:201
    at new Promise (<anonymous>)
    at e.t.decodeFromImage (BrowserCodeReader.ts:192)
    at HTMLAnchorElement.document.getElementById.addEventListener ((index):70)
(index):77 Started decode for image from http://localhost:8888/qr-image/test0.jpg
BrowserCodeReader.ts:257 true Error
    at t.readVersion (BitMatrixParser.ts:140)
    at t.decodeBitMatrixParser (Decoder.ts:130)
    at t.decodeBitMatrix (Decoder.ts:84)
    at t.decode (QRCodeReader.ts:76)
    at e.t.readerDecode (BrowserCodeReader.ts:278)
    at e.t.decodeOnce (BrowserCodeReader.ts:254)
BrowserCodeReader.ts:262 checksum or format error, trying again... Error
    at t.readVersion (BitMatrixParser.ts:140)
    at t.decodeBitMatrixParser (Decoder.ts:130)
    at t.decodeBitMatrix (Decoder.ts:84)
    at t.decode (QRCodeReader.ts:76)
    at e.t.readerDecode (BrowserCodeReader.ts:278)
    at e.t.decodeOnce (BrowserCodeReader.ts:254)
```

**Comment by odahcam** [comment]
Ok, I'll wait for the CodePen example then.

**Comment by dodomui** [comment]
Erm... I tried to create a CodePen but receiving cross origin error. Any idea how could I solve it?
`SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.`

For my case, is not all QR code cannot decode, just some of the QR code unable to decode...
And I'm using exactly the same from example... wonder is I do anything wrong...

**Comment by odahcam** [comment]
I couldn't decode it as well, it returns a Promise that never gets resolved. 😠 

Could it be related to #76?

**Comment by dodomui** [comment]
Something different is, not all QR code image cannot be decoded.
I can decode most of the QR code successfully, just some of QR code format cannot be decode properly. Cannot find out what's wrong...

**Comment by JasonHK** [comment]
Hello, I have the same problem using the library. The below images are the same QR code but taken differently. Both of them are able to be decoded by [ZXing Decoder Online](https://zxing.org/w/decode.jspx), but failed on this library. I thought this was a direct port of the original ZXing Java library...

Here's the error that the library threw:
```
FormatException
    at Function.DecodedBitStreamParser.decode (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/@zxing/library/esm5/core/qrcode/decoder/DecodedBitStreamParser.js:123:19)
    at Decoder.decodeBitMatrixParser (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/@zxing/library/esm5/core/qrcode/decoder/Decoder.js:131:49)
    at Decoder.decodeBitMatrix (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/@zxing/library/esm5/core/qrcode/decoder/Decoder.js:70:25)
    at QRCodeReader.decode (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/@zxing/library/esm5/core/qrcode/QRCodeReader.js:65:42)
    at /home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/lib/load.js:18:35
    at Generator.next (<anonymous>)
    at fulfilled (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/tslib/tslib.js:107:62)
```
```
ChecksumException
    at Decoder.correctErrors (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/@zxing/library/esm5/core/qrcode/decoder/Decoder.js:154:19)
    at Decoder.decodeBitMatrixParser (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/@zxing/library/esm5/core/qrcode/decoder/Decoder.js:125:18)
    at Decoder.decodeBitMatrix (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/@zxing/library/esm5/core/qrcode/decoder/Decoder.js:70:25)
    at QRCodeReader.decode (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/@zxing/library/esm5/core/qrcode/QRCodeReader.js:65:42)
    at /home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/lib/load.js:18:35
    at Generator.next (<anonymous>)
    at fulfilled (/home/jasonhk/Programming/NodeJS/Games/Pokemon/Super Secret Base/node_modules/tslib/tslib.js:107:62)
```
<br>

![20190725_173833](https://user-images.githubusercontent.com/4410086/61890099-5aa0e000-af39-11e9-8684-958e2b0983fe.jpg)
![20190725_173854](https://user-images.githubusercontent.com/4410086/61890107-5ffe2a80-af39-11e9-8db9-9311fc4409b8.jpg)

**Comment by odahcam** [comment]
This is a direct port, but you can't expect two completely different engines to produce the same result. Also, I was able to decode both images with the [demo application](https://zxing-js.github.io/library/). Checksum and Format errors are very common, once they can be generated by any external influences like movement and ilumination. Have you tried to decode these images using the Node APIs as you are doing with the Java version?

As this issue is too broad and lived too much, I'm closing this now because it's not an error with the library itself.

Feel free to contact-me for help or open a new issue if you think you found an error.

**Comment by Krammig** [comment]
The first QR code displayed above is missng the  "data:image/png;base64,"  designation at the front of the string thus making it difficult if not impossible for most readers to identify as it will just appeaer as a strinf of data.

**Comment by ancikudi1** [comment]
What is QR code
